# _quarto.yml
project:
  type: book
  output-dir: docs

book:
  title: "Modelado de la Diabetes Tipo 2"
  author:
  - name: Carlos Eduardo Chacón Rodríguez
    email: carlos.chacon78@unach.mx
    corresponding: true
  - name: Yofre Hernán García Gómez
    degrees: PhD
    email: yofre.garcia@unach.mx
    roles: investigador
    corresponding: true
  date: "junio 2025"
  chapters:
    - index.qmd
    - resumen.qmd
    - fundamento_fisio.qmd
    #- modelo.qmd
    #- resultados.qmd
    #- conclusiones.qmd

  sidebar:
    #logo: unach-logo.png
    search: true
    style: "floating"
