project:
  type: book
  output-dir: docs
book:
  title: "Modelado de la Diabetes Tipo 2 mediante Ecuaciones Diferenciales con retardo"
  author:
    - name: Carlos Eduardo Chacón Rodríguez
      email: carlos.chacon78@unach.mx
      corresponding: true
    - name: Yofre Hernán García Gómez
      degrees: PhD
      email: yofre.garcia@unach.mx
      roles: [Revisor]
      corresponding: true
  date: "junio 2025"
  chapters:
    - index.qmd
    - resumen.qmd
    - fundamento_fisio.qmd
    - modelos.qmd
    # - resultados.qmd
    # - conclusiones.qmd

  sidebar:
    logo: logo-DELFIN.png
    search: true
    style: "floating"
    collapse-level: 1
    pinned: true

  downloads: 
    - pdf

  page-navigation: true
  page-footer:
    left: "© 2025 Carlos Eduardo Chacón Rodríguez"
    right: "Hecho con [Quarto](https://quarto.org)"

format:
  html:
    theme: darkly
     # light: cosmo
      #dark: darkly
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css
  pdf:
    documentclass: book
    include-in-header: latex/preamble.tex
    toc: true
    number-sections: true
    mainfont: Latin Modern Roman
    fontsize: 12pt
    geometry: a4paper
    output-file: proyecto_delfin